name: Trigger Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write
  actions: write

jobs:
  run-down-bot:
    runs-on: ubuntu-latest

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}
      IMG_TOKEN: ${{ secrets.IMG_TOKEN }}
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: install imagemagick
        run: sudo apt-get install -y imagemagick

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
          architecture: x64 

      - name: Is it already running?
        run: |
          WORKFLOW_NAME="${{ github.workflow }}"
          RUN_COUNT=$(gh run list --status=in_progress --json name |
            jq "[.[] | select(.name == \"$WORKFLOW_NAME\")] | length")

          if [ "$RUN_COUNT" -gt 1 ]; then
            echo "The workflow is already running, so we are not going to start it again"
            exit 0
          else
            echo "The workflow is not running, so we are going to start it"
          fi
        
      - name: Upgrade pip to latest stable
        run: |
          python -m pip install --upgrade pip
        
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Sync with remote to avoid diverging history
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
      
      - name: Update replyed_ids.txt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated"
          file_pattern: replyed_ids.txt
          push_options: '--force'

      - name: Activate the workflow
        run: |
          set -e
      
          REPO="${{ github.repository }}"
          BRANCH_NAME="${{ github.ref_name }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          API_URL="https://api.github.com/repos/$REPO/actions"
      
          echo "Repository: $REPO"
          echo "Branch Name: $BRANCH_NAME"
      
          # Verifica se o 'jq' está disponível
          if ! command -v jq &> /dev/null; then
            echo "Erro: 'jq' não está instalado. Instale para continuar."
            exit 1
          fi
      
          # Função para obter o ID do primeiro workflow
          get_workflow_id() {
            curl -s -H "Authorization: Bearer $TOKEN" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "$API_URL/workflows" | jq -r '.workflows[0].id'
          }
      
          # Função para disparar o workflow
          trigger_workflow() {
            curl -s -o response_body.txt -w "%{http_code}" -X POST \
              -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"ref\":\"$BRANCH_NAME\"}" \
              "$API_URL/workflows/$1/dispatches"
          }
      
          WORKFLOW_ID=$(get_workflow_id)
          echo "Workflow ID: $WORKFLOW_ID"
      
          # Tentar disparar o workflow com até 3 tentativas
          max_retries=3
          for attempt in $(seq 1 $max_retries); do
            response=$(trigger_workflow "$WORKFLOW_ID")
            echo "Tentativa $attempt: HTTP $response"
            cat response_body.txt
      
            if [[ $response -ge 200 && $response -lt 300 ]]; then
              echo "Workflow triggered successfully!"
              exit 0
            else
              echo "Erro ao disparar o workflow. Nova tentativa em 5 segundos..."
              sleep 5
            fi
          done
      
          echo "Falha ao disparar o workflow após $max_retries tentativas."
          exit 1
      
